export const settings = {
  selectors: {
    navigation: '.navigation',
    footer: '.footer',
    navigationCheckbox: "menu-toggle",
    contactButton: '.contact__btn',
    contactButtonText: '.contact__btn-text',
    contactBox: '.contact__box',
    closeButton: '.close__trigger',
    carousel: 'carousel',
    galleryItem: 'gallery-item',
    imagesBox: '.images',
    images: 'img',
    div: 'div',
    src: 'src',
    dataIndex: 'data-index',
    jsCarousel: '.js-carousel',
    jsCarouselBgImg: '.js-carousel-bg-img',
    jsCarouselList: '.js-carousel-list',
    jsCarouselListItem: '.js-carousel-list-item',
    isVisible: '.is-visible',
    langChangeTrigger: '.lang-change',
    langEnglish: '.eng',
    langPolish: '.pol',
  },
  classes: {
    boxActive: 'box__active',
    buttonActive: 'button__active',
    lightbox: 'lightbox',
    lightboxContent: 'lightbox-content',
    lightboxPrev: 'lightbox-prev',
    lightboxNext: 'lightbox-next',
    fa: 'fa',
    faAngleLeft: 'fa-angle-left',
    faAngleRight: 'fa-angle-right',
    imageActive: 'image__active',
    navigationHide: 'navigation__hide',
    footerShow: 'footer__show',
    isVisible: 'is-visible',
  },
  atributes: {
    en: 'en',
    pl: 'pl',
    lang: 'lang',
  },
  styles: {
    displayNone: 'none',
    displayBlock: 'block',
    opacity0: '0',
    opacity1: '1',
  },
  pictures: {
    about: ['../../images/about/about1.jpg',
            '../../images/about/about2.jpg',
            '../../images/about/about3.jpg',
            '../../images/about/about4.jpg',
    ],
  }
}

export default settings;
